In [1]:
print("Hello World, testing out jupyter notebook!")

Hello World, testing out jupyter notebook!


In [3]:
import pandas as pd
import numpy as np

In [3]:
x = np.array([1,2,3,4,5], dtype=float)
print(x)
# first numpy array

[1. 2. 3. 4. 5.]


In [4]:
print(x)

[1. 2. 3. 4. 5.]


In [5]:
p = np.array([4, 24, 5, 43, 68], dtype=float)
print(p)

[ 4. 24.  5. 43. 68.]


In [6]:
type(p)

numpy.ndarray

In [7]:
print(5*p)

[ 20. 120.  25. 215. 340.]


In [8]:
z = 5 * p
# testing out operations with numpy arrays

In [ ]:
z

In [10]:
print(z)

[ 20. 120.  25. 215. 340.]


In [11]:
np.sum(z)

720.0

In [12]:
z > 10
# returns array with booleans

array([ True,  True,  True,  True,  True])

In [13]:
z > 25

array([False,  True, False,  True,  True])

In [14]:
z[z>30]

array([120., 215., 340.])

In [15]:
print(np.pi)

3.141592653589793


In [16]:
np.log2(z)

array([4.32192809, 6.9068906 , 4.64385619, 7.74819285, 8.40939094])

In [17]:
np.log10(z)

array([1.30103   , 2.07918125, 1.39794001, 2.33243846, 2.53147892])

In [333]:
print("Experimenting with too much log....")
#np.log120(z)
# this caused an error


Experimenting with too much log....


In [19]:
# higher log values does not exist with numpy
a = pd.Series([1, 2, 3, 4, 5, 6])

In [20]:
a

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [21]:
type(a.values)

numpy.ndarray

In [22]:
np.sum(a.values)

21

In [23]:
a.index

RangeIndex(start=0, stop=6, step=1)

In [24]:
print(a.index)

RangeIndex(start=0, stop=6, step=1)


In [25]:
players = pd.Series([28, 30, 27, 28], index=["Anthony Davis", "James Harden", "LeBron James", "Damian Lilliard"])
print(players)

Anthony Davis      28
James Harden       30
LeBron James       27
Damian Lilliard    28
dtype: int64


In [26]:
players[players> 28]
# the games leading scorer and 'MVP'

James Harden    30
dtype: int64

In [27]:
topscore = list(players.values)

In [28]:
topscore

[28, 30, 27, 28]

In [29]:
print(max(topscore))

30


In [30]:
print(min(topscore))

27


In [31]:
"Anthony Davis" in players

True

In [32]:
"Bob Simmons" in players

False

In [5]:
"LeBron James" in players
# more testing

True

In [4]:
players = pd.Series([28, 30, 27, 28], index=["Anthony Davis", "James Harden", "LeBron James", "Damian Lilliard"])
print(players)


Anthony Davis      28
James Harden       30
LeBron James       27
Damian Lilliard    28
dtype: int64


In [6]:
"LeBron James" in players

True

In [7]:
players[players > 28]

James Harden    30
dtype: int64

In [8]:
players[players > 27]

Anthony Davis      28
James Harden       30
Damian Lilliard    28
dtype: int64

In [9]:
elDict = {'players':["Matthew Strong", ""]}

In [10]:
elDict

{'players': ['Matthew Strong', '']}

In [11]:
elDict = {'players':["Matthew Strong", "LeBron James", "Joel Embiid", "Michael Jordan"], 'PPG':[1, 27, 20, 30], 'Team':["Baby Bobby Ballers", "Los Angeles Lakers", "Philadelphia 76ers"]}

In [12]:
elDict

{'PPG': [1, 27, 20, 30],
 'Team': ['Baby Bobby Ballers', 'Los Angeles Lakers', 'Philadelphia 76ers'],
 'players': ['Matthew Strong',
  'LeBron James',
  'Joel Embiid',
  'Michael Jordan']}

In [273]:
#data = pd.DataFrame(elDict)

In [14]:
elDict = {'players':["Matthew Strong", "LeBron James", "Joel Embiid", "Michael Jordan"], 'PPG':[1, 27, 20, 30], 'Team':["Baby Bobby Ballers", "Los Angeles Lakers", "Philadelphia 76ers", "Chicago Bulls"]}

In [15]:
elDict

{'PPG': [1, 27, 20, 30],
 'Team': ['Baby Bobby Ballers',
  'Los Angeles Lakers',
  'Philadelphia 76ers',
  'Chicago Bulls'],
 'players': ['Matthew Strong',
  'LeBron James',
  'Joel Embiid',
  'Michael Jordan']}

In [16]:
dataNBA = pd.DataFrame(elDict)

In [17]:
dataNBA

PPG                Team         players
0    1  Baby Bobby Ballers  Matthew Strong
1   27  Los Angeles Lakers    LeBron James
2   20  Philadelphia 76ers     Joel Embiid
3   30       Chicago Bulls  Michael Jordan

In [18]:
print(dataNBA)

   PPG                Team         players
0    1  Baby Bobby Ballers  Matthew Strong
1   27  Los Angeles Lakers    LeBron James
2   20  Philadelphia 76ers     Joel Embiid
3   30       Chicago Bulls  Michael Jordan


In [19]:
dataNBA

PPG                Team         players
0    1  Baby Bobby Ballers  Matthew Strong
1   27  Los Angeles Lakers    LeBron James
2   20  Philadelphia 76ers     Joel Embiid
3   30       Chicago Bulls  Michael Jordan

In [20]:
dataNBA.head(2)

PPG                Team         players
0    1  Baby Bobby Ballers  Matthew Strong
1   27  Los Angeles Lakers    LeBron James

In [334]:
# (deleted)


In [22]:
playersSorted = dataNBA.sort_values(by="PPG", ascending=False)
playersSorted

PPG                Team         players
3   30       Chicago Bulls  Michael Jordan
1   27  Los Angeles Lakers    LeBron James
2   20  Philadelphia 76ers     Joel Embiid
0    1  Baby Bobby Ballers  Matthew Strong

In [23]:
dataNBA["PPG"] > 20

0    False
1     True
2    False
3     True
Name: PPG, dtype: bool

In [25]:
dataNBA["PPG"] > 15

0    False
1     True
2     True
3     True
Name: PPG, dtype: bool

In [26]:
p = pd.Series(dataNBA["PPG"] > 15)

In [27]:
p

0    False
1     True
2     True
3     True
Name: PPG, dtype: bool

In [272]:
dataNBA.groupby("PPG")

In [29]:
dataNBA.groupby("PPG")

In [30]:
print(dataNBA.groupby("PPG"))

In [31]:
dataNBA

PPG                Team         players
0    1  Baby Bobby Ballers  Matthew Strong
1   27  Los Angeles Lakers    LeBron James
2   20  Philadelphia 76ers     Joel Embiid
3   30       Chicago Bulls  Michael Jordan

In [32]:
dataNBA["PPG"]

0     1
1    27
2    20
3    30
Name: PPG, dtype: int64

In [33]:
dataNBA["PPG"].apply(lambda x: x +1)

0     2
1    28
2    21
3    31
Name: PPG, dtype: int64

In [34]:
dataNBA


PPG                Team         players
0    1  Baby Bobby Ballers  Matthew Strong
1   27  Los Angeles Lakers    LeBron James
2   20  Philadelphia 76ers     Joel Embiid
3   30       Chicago Bulls  Michael Jordan

In [35]:
dataNBA["PPG"]

0     1
1    27
2    20
3    30
Name: PPG, dtype: int64

In [36]:
dataNBA["PPG"] = dataNBA["PPG"].apply(lambda x: x +1)
# testing lamba

In [37]:
dataNBA 

PPG                Team         players
0    2  Baby Bobby Ballers  Matthew Strong
1   28  Los Angeles Lakers    LeBron James
2   21  Philadelphia 76ers     Joel Embiid
3   31       Chicago Bulls  Michael Jordan

In [38]:
from sklearn import svm
# moving on to svm 

In [39]:
X = [[0,0], [2,2]]
y=[2.5, 4.5]
client = svm.SVR()
# support vector regression

In [40]:
client.fit(X,y)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
  kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [271]:
print("More testing on the way....")

More testing on the way....


In [42]:
client.predict([[1,1]])

array([3.5])

In [43]:
client.predict([[5,5]])

array([3.50011314])

In [45]:
client.predict([[2,2]])

array([4.4])

In [46]:
vo = np.array([1, 2, 4])

In [47]:
vo


array([1, 2, 4])

In [48]:
print(vo)

[1 2 4]


In [49]:
print([1, 2, 4])

[1, 2, 4]


In [270]:
clr = svm.SVR()


In [62]:
X = [[0,0], [2,2], [3,3]]
y=[2.5, 4.5]
client = svm.SVR()

In [346]:
X=[[0,0], [1,1], [2,2], [3,3], [4,4]]
y=[0,0.5, 1, 1.5, 2]
client = svm.SVR(kernel='linear')
client.fit(X,y)
#print("{} and {}".format(X,y))


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
  kernel='linear', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [348]:
client.predict([[2.5, 2.5]])


array([1.225])

In [355]:
print("Hi")
client.predict([[2.75, 2.75]])
# ...
x = client.score([[2.5, 2.5]], [1.225])
val = int(x *100)
print("{} was the score out of 100".format(val))

Hi
100 was the score out of 100


In [90]:
# some simple linear regression here 
normLinear = svm.SVR(kernel="linear")
X=[[0,0], [1,1], [2,2]]
y=[3.5,7.5, 11.5]
normLinear.fit(X,y)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
  kernel='linear', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [93]:
normLinear.predict([[2.5,2.5]])

array([13.35])

In [94]:
import json
import requests
# testing json and requests here

In [95]:
response = requests.get("https://jsonplaceholder.typicode.com/todos")


In [96]:
print(response)

<Response [200]>


In [340]:
#print("{} is the text of the response.".format(response.text))

In [98]:
todos = json.loads(response.text)

In [100]:
print("hi")

hi


In [104]:
todos[0]['completed']
# everything is put into dictionaries!

False

In [105]:
x = np.array([[72, 200], [70, 180], [69, 179], [80, 250], [84, 300], [81, 270]])
y = np.array(["Point Guard", "Point Guard", "Point Guard", "Center", "Center", "Center"])

In [106]:
clf = svm.SVC()
clf.fit(x, y) 

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [113]:
clf.predict([[82,190]])

array(['Center'], dtype='<U11')

In [118]:
newRep = requests.get("http://data.nba.net/10s/prod/v1/2018/players.json")

In [343]:

# print(newRep.text) ... would have printed out all of the the nba players, uncommenting and run this section to see the results.

In [121]:
allPlayers = json.loads(newRep.text)

In [341]:
#allPlayers

In [342]:
#print(allPlayers['league']['standard'])
# looking at all of the players

In [132]:
# we want to choose between G F and C
x = np.array([1,2,3])

In [140]:
x = np.append(x,[[1]])
print(x)
y = np.array([])
print(y)




[1 2 3 1 1 1 1]
[]


In [339]:
playerSize = np.array([[0,0]])
playerPosition = np.array([])
testing = np.array([])
for i in allPlayers['league']['standard']:
    skip = False
    if(i['weightPounds'] == '' or i['heightFeet']=='' or i['heightInches']==''):
        skip = True
    if(not skip):
        totalHeight = (int(i['heightFeet'])*12) + int(i['heightInches'])
        #fullName = i['firstName'] + ' ' + i['lastName']
        #print('{} is {} inches tall.'.format(fullName, totalHeight))
        #print([int(i['weightPounds']), totalHeight])
        arr = np.array([[int(i['weightPounds']), totalHeight]])
        xEr = np.array([int(i['weightPounds']), totalHeight])
        #print(arr)
        #print(i['pos'])
        #print(playerSize)
        playerSize = np.concatenate((playerSize, arr))
        testing = np.append(testing, xEr)
        #playerSize = np.append(playerSize, [int(i['weightPounds']), totalHeight])
        playerPosition = np.append(playerPosition, i['pos'])

#realPlayerSize = playerSize[playerSize!=[0,0]]
y = np.expand_dims(playerSize, axis=1)

realPlayers = playerSize[1:]
print(realPlayers)

clf = svm.SVC()

clf.fit(realPlayers, playerPosition)
#print(clf)
print(clf)
clf.predict([[260, 82]])
clf.score([[260, 82], [250, 80]], ['C', 'C'])
#score matches up what the svm thinks the answer is vs. what is actually provided to it
import matplotlib.pyplot as plt
print(testing.size)
print(playerPosition.size)

# testing out the functions



[[190  78]
 [240  79]
 [190  74]
 ...
 [250  84]
 [250  83]
 [240  85]]
SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)
SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)
1096
548


In [338]:
# final version

import json
import requests

import pandas as pd
import numpy as np


# Matthew Strong CU Boulder
# July 21 2018
# NBA Data API used 
# uses SVC machine learning to predict the best position for a person who wants to see if they have 'NBA' level height and weight
# indeed the average height of a man would be very low for this function


def predictPosition():
    
    newRep = requests.get("http://data.nba.net/10s/prod/v1/2018/players.json")
    allPlayers = json.loads(newRep.text)
    # loading all of the players into python dictionary with the data nba api
    playerSize = np.array([[0,0]])
    # setting the numpu arrays
    playerPosition = np.array([])
    for i in allPlayers['league']['standard']:
        skip = False
        if(i['weightPounds'] == '' or i['heightFeet']=='' or i['heightInches']==''):
            skip = True
            # if a weight or height aspect of the player is visibly missing, skip the player
        if(not skip):
            # calculates total height
            totalHeight = (int(i['heightFeet'])*12) + int(i['heightInches'])
            #fullName = i['firstName'] + ' ' + i['lastName']
            #print('{} is {} inches tall.'.format(fullName, totalHeight))
            #print([int(i['weightPounds']), totalHeight])
            
            # array of the weight and full height
            arr = np.array([[int(i['weightPounds']), totalHeight]])
            #print(arr)
            #print(playerSize)
            # adding the height and weight duo to the np array of every player
            playerSize = np.concatenate((playerSize, arr))
            #playerSize = np.append(playerSize, [int(i['weightPounds']), totalHeight])
            
            #adding player position here to array -
            # options are center, forward, or guard or combo of any two except guard-center
            playerPosition = np.append(playerPosition, i['pos'])   
    # getting rid of the [0,0] placeholder
    realPlayers = playerSize[1:]
    #print(realPlayers)
    clf = svm.SVC()
    # new instance of svc
    # fit array of player's weight/heights to their corresponding position
    clf.fit(realPlayers, playerPosition)         
    weight = 0
    heightFeet = 0
    heightInches = 0
    # the next few while loops will get the user's height and weight and will check for failure to convert to int
    # e.g. the user types in 'swol' for weight
    while(1):
        weight = input("What is your weight in pounds? ")
        try:
            weight = int(weight)
            break
        except ValueError:
            print("Please enter in a number! ")
    while(1):
        heightFeet = input("What is your height? Enter feet first. ")
        try:
            heightFeet = int(heightFeet)
            
            break
        except ValueError:
            print("Please enter in a number! ")
    while(1):
        heightInches = input("What is your height? Now enter inches. ")
        try:
            heightInches = int(heightInches)
            break
        except ValueError:
            print("Please enter in a number!")
    totalHeight = (heightFeet*12) + heightInches
    # predicts the user's classification based on weight and height and reads the position referencing a dictionary
    rest = clf.predict([[weight, totalHeight]])
    #print(rest[0])
    myDict = {'F':"Forward", 'G':'Guard', 'C':"Center", 'G-F':"Primary Guard and Secondary Forward", 'F-G':"Primary Forward and Secondary Guard", 'F-C':"Primary Forward and Secondary Center", 'C-F':"Primary Center and Secondary Forward"}
    selection = myDict[rest[0]]
    print("Based on the Stats of ALL of the NBA Players, and your height and weight, you should be a {}.".format(selection))
    #print("{} is the weight".format(weight))
    #print("{} is the height in feet".format(heightFeet))
    #print("{} is the height in inches".format(heightInches))
# press shift+enter to run this section of code as well as the function

predictPosition()


What is your weight in pounds? 260
What is your height? Enter feet first. 7
What is your height? Now enter inches. 1
Based on the Stats of ALL of the NBA Players, and your height and weight, you should be a Center.


In [363]:
x = np.array([["run", "bike", "swim"], ["sit", "watch", "lie"]])
print(x.shape)
print("{1} is the second option, and {0} is the first option".format("run", "bike"))
# testing strings

(2, 3)
bike is the second option, and run is the first option


In [ ]:
import json
import requests





In [415]:
x = np.array([[1, 2]])
b = np.array([[4, 4]])
x = np.concatenate((x, b))
print(x)
listo 
years = ['2011', '2012', '2013', '2014', '2015', '2016', '2017']


#url = "http://data.nba.net/json/cms/" + str


# time to show that the west is best
newRep = requests.get("http://data.nba.net/json/cms/2013/standings/division.json")
# gets all of the divisions from 2013 and will take a look at the team's record..
standings = json.loads(newRep.text)
divisions = standings['sports_content']['standings']['conferences']
# connection here takes too long... why?
arr = []

for i in divisions:
    
    
for region in arr:
    print(divisions[region]['divisions'])

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [449]:
print("This is hard to watch")
newRep = requests.get("http://data.nba.net/json/cms/2014/standings/division.json")

This is hard to watch


In [ ]:
print("hello")
x = "http://data.nba.net/json/cms/" + "2014" + "/standings/division.json"
print(x)

In [15]:
import math
import json
import requests
import numpy as np

def nbaAnalysis():
    # run years from 2011 - 2017
    yearArray = ['2011', '2013', '2014', '2015', '2016', '2017']
    
    playoffStats = np.array([[1, 1, 1, 1, 1]])
    winAmount = np.array([])
    
    
    confDict = {'East':0, 'West':1}
    # in the code for the user we cannot have 'west' and 'central' here
    divDict = {'Atlantic':1, 'Central':2, 'Southeast':3, 'Northwest':4, 'Pacific':5, 'Southwest':6}
    
    
    for year in yearArray:
        url = "http://data.nba.net/json/cms/" + year + "/standings/division.json"
        print(year)
        print(url)
        newRep = requests.get(url)
        standings = json.loads(newRep.text)
        divisions = standings['sports_content']['standings']['conferences']
        for i in divisions:
            for name in divisions[i]['divisions']:
                # specifies each division      
                print(name)
                for z in (divisions[i]['divisions'][name]['team']):
                        #print(z)
                        teamName = z['name'] + ' ' + z['nickname']
                        tWins = int(z['team_stats']['wins'])
                        tLosses = int(z['team_stats']['losses'])
                        ratio = tWins/(tWins + tLosses)
                        winPercent  = (round(ratio,4))
                        print("{} had a record of {}-{} with percentage of {}.".format(teamName, tWins, tLosses, winPercent))
                        inPlayoffs = (int(z['team_stats']['clinched_playoffs']))
                        bestDivision = (int(z['team_stats']['clinched_division']))
                        topConference = (int(z['team_stats']['clinched_conference']))
                        teamNumpy = np.array([[inPlayoffs, bestDivision, topConference, int(confDict[i]), int(divDict[name])]])
                        #print(teamNumpy)
                        winAmount = np.append(winAmount, winPercent)
                        #print(winAmount)
                        playoffStats = np.concatenate((playoffStats, teamNumpy))


    actualPlayoffStats = playoffStats[1:]
    print(actualPlayoffStats)
    nbaClient = svm.SVR(C=0.77)
    nbaClient.fit(actualPlayoffStats, winAmount)
    lowerConfDict = {'east':0, 'west':1}
    # in the code for the user we cannot have 'west' and 'central' here
    lowerDivDict = {'atlantic':1, 'central':2, 'southeast':3, 'northwest':4, 'pacific':5, 'southwest':6}
    inputvalues = [[]]
    west = ['northwest', 'pacific', 'southwest']
    east = ['atlantic', 'central', 'southeast']
    isWest = False
    while(1):
        conf = input("Choose a Conference: West or East. ")
        if(conf.lower() == 'west' or conf.lower() == 'east'):
            inputvalues[0].append(lowerConfDict[conf.lower()])
            if(conf.lower() == 'west'):
                isWest = True

            break
        else:
            print("Please enter a conference: ")
    while(1):
        if(isWest):
            print("Northwest")
            print("Pacific")
            print("Southwest")

            div = input("Type the West division: ")
            if(div.lower() in west):
                inputvalues[0].append(lowerDivDict[div.lower()])
                break
            else:
                print("Please enter a correct division: ")       

        else:
            print("Atlantic")
            print("Central")
            print("Southeast")

            div = input("Type the East division: ")
            if(div.lower() in east):
                inputvalues[0].append(lowerDivDict[div.lower()])
                break
            else:
                print("Please enter a correct division: ")


    while(1):
        answer = input("Do you want the team in the NBA playoffs? ")
        if(answer.lower() == 'yes'):
            break
        elif(answer.lower() == 'no'):
            po = nbaClient.predict([[0,0,0,inputvalues[0][0], inputvalues[0][1]]])
            wins = po[0] * 82
            realTimeWins = math.ceil(wins)
            print("Based on these conditions, this  non-playoff  team is expected to have a record of {}-{}. ".format(realTimeWins, 82-realTimeWins))
            # we can assume everything else here is 0
            return
            # this is the average non-playoff team
        else:
            print("Please enter a valid answer. ")



    while(1):
        answer = input("Do you want the team at the top of their division? ")
        if(answer.lower() == 'yes'):
            break
        elif(answer.lower() == 'no'):
            po = nbaClient.predict([[1,0,0,inputvalues[0][0], inputvalues[0][1]]])
            wins = po[0] * 82
            realTimeWins = math.ceil(wins)
            print("Based on these conditions, this decent playoff team is expected to have a record of {}-{}. ".format(realTimeWins, 82-realTimeWins))
            return
            # we can assume everything else here is 0
            # this is the playoff team that doesn't win the division
        else:
            print("Please enter a valid answer. ")


    while(1):
        answer = input("Do you want the team at the top of the conference? ")
        if(answer.lower() == 'yes'):

            inputvalues[0].append(1)
            po = nbaClient.predict([[1,1,1,inputvalues[0][0], inputvalues[0][1]]])
            wins = po[0] * 82
            realTimeWins = math.ceil(wins)
            print("Based on these conditions, this  elite playoff  team is expected to have a record of {}-{}. ".format(realTimeWins, 82-realTimeWins))
            return
            # can do the rest here
        elif(answer.lower() == 'no'):
            inputvalues[0].append(0)
            po = nbaClient.predict([[1,1,0,inputvalues[0][0], inputvalues[0][1]]])
            wins = po[0] * 82
            realTimeWins = math.ceil(wins)
            print("Based on these conditions, this good playoff team is expected to have a record of {}-{}. ".format(realTimeWins, 82-realTimeWins))
            return
            # we can assume everything else here is 0
            # this is the playoff team that doesn't win the division
        else:
            print("Please enter a valid answer. ")        

nbaAnalysis()
        
        




2011
http://data.nba.net/json/cms/2011/standings/division.json
Atlantic
Boston Celtics had a record of 39-27 with percentage of 0.5909.
New York Knicks had a record of 36-30 with percentage of 0.5455.
Philadelphia 76ers had a record of 35-31 with percentage of 0.5303.
Toronto Raptors had a record of 23-43 with percentage of 0.3485.
New Jersey Nets had a record of 22-44 with percentage of 0.3333.
Central
Chicago Bulls had a record of 50-16 with percentage of 0.7576.
Indiana Pacers had a record of 42-24 with percentage of 0.6364.
Milwaukee Bucks had a record of 31-35 with percentage of 0.4697.
Detroit Pistons had a record of 25-41 with percentage of 0.3788.
Cleveland Cavaliers had a record of 21-45 with percentage of 0.3182.
Southeast
Miami Heat had a record of 46-20 with percentage of 0.697.
Atlanta Hawks had a record of 40-26 with percentage of 0.6061.
Orlando Magic had a record of 37-29 with percentage of 0.5606.
Washington Wizards had a record of 20-46 with percentage of 0.303.
Charl

Atlantic
Boston Celtics had a record of 53-29 with percentage of 0.6463.
Toronto Raptors had a record of 51-31 with percentage of 0.622.
New York Knicks had a record of 31-51 with percentage of 0.378.
Philadelphia 76ers had a record of 28-54 with percentage of 0.3415.
Brooklyn Nets had a record of 20-62 with percentage of 0.2439.
Central
Cleveland Cavaliers had a record of 51-31 with percentage of 0.622.
Milwaukee Bucks had a record of 42-40 with percentage of 0.5122.
Indiana Pacers had a record of 42-40 with percentage of 0.5122.
Chicago Bulls had a record of 41-41 with percentage of 0.5.
Detroit Pistons had a record of 37-45 with percentage of 0.4512.
Southeast
Washington Wizards had a record of 49-33 with percentage of 0.5976.
Atlanta Hawks had a record of 43-39 with percentage of 0.5244.
Miami Heat had a record of 41-41 with percentage of 0.5.
Charlotte Hornets had a record of 36-46 with percentage of 0.439.
Orlando Magic had a record of 29-53 with percentage of 0.3537.
Northwest
U

In [3]:
from sklearn import svm
import numpy as np

In [4]:
print("hiL")

hiL
